Homework27
BorisIurciuc/homework pull request #4
Opened 2023-11-11 18:33 UTC by BorisIurciuc

2023-11-11 18:53 UTC, pod1425 requested changes

2023-11-11 18:53 UTC, pod1425 commented on src/homework27/task02/BankAccount.java
> +  private int cashFlows;                // Сумма для перечисления
сумма для перечисления не является характеристикой банковского счета. Не должна быть записана как поле

2023-11-11 18:53 UTC, pod1425 commented on src/homework27/task02/BankAccount.java
> +  public void pullMoneyAmount() {                         // Снять со счёта
должно передаваться как параметр

2023-11-12 11:05 UTC, BorisIurciuc commented on src/homework27/task02/BankAccount.java
> +  private int cashFlows;                // Сумма для перечисления
исправлено,  переменная "cashFlows"  удалена, спользуется переменная "cash"  класса Main

2023-11-12 11:05 UTC, BorisIurciuc commented on src/homework27/task02/BankAccount.java
> +  public void pullMoneyAmount() {                         // Снять со счёта
исправлено,  переменная "cash"  класса Main передается как параметр метода

2023-11-13 07:27 UTC, pod1425 commented on src/homework27/task02/BankAccount.java
> +  private int moneyAmount = 10;         // Текущая сумма на счете
начальная сумма - 0

2023-11-13 07:29 UTC, merged